### ISSUE TITLE
NEII - Apr 2021 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#178]
- [x] update to latest terriajs next
- [x] Global Horizontal Exposure not loading (WMS): https://github.com/TerriaJS/neii-viewer/issues/172
- [x] Wrong error message for NEMSR catalogue item: https://github.com/TerriaJS/neii-viewer/issues/171 
- [x] Geofabric datasets errors: https://github.com/TerriaJS/neii-viewer/issues/170 - See https://github.com/TerriaJS/neii-viewer/issues/170#issuecomment-823009029
- [x] Update Hydrology and Marine points url from GA: https://github.com/TerriaJS/neii-viewer/issues/169 - see https://github.com/TerriaJS/neii-viewer/issues/169#issuecomment-823015442

**Comment by AnaBelgun** [comment]
@AnaBelgun to test all the tickets against the new version of NEII based on latest next.

**Comment by nf-s** [comment]
Things to do for NEII:

- [ ] Run catalog through `catalog-converter`
- [ ] Fix branding

<img src="https://user-images.githubusercontent.com/6187649/114670236-204b2800-9d46-11eb-9311-8aecae0dc6ff.png" height="200px"/> To match <img src="https://user-images.githubusercontent.com/6187649/114670341-3ce76000-9d46-11eb-92d9-980e4226ef3f.png" height="200px"/>

**Comment by AnaBelgun** [comment]
Needs an update 28 Apr 2021

**Comment by AnaBelgun** [comment]
release sent to NEII on 3 may 2021
