### ISSUE TITLE
NEII - May 2021 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#183]
- [ ] SOS layers fail: https://github.com/TerriaJS/neii-viewer/issues/168
- [ ] NEMSR feature info templates not working https://github.com/TerriaJS/neii-viewer/issues/167
- [ ] dot points for CSV data are too big compare to v7 version: https://github.com/TerriaJS/neii-viewer/issues/166
- [ ] Victorian soil WMS too big: https://github.com/TerriaJS/neii-viewer/issues/165

- [ ] radio buttons - https://github.com/terriajs/terriajs/issues/5037
- [ ] ideal zoom - https://github.com/terriajs/terriajs/issues/5047
- [ ] SOS catalogue item - https://github.com/terriajs/terriajs/issues/5045
- [ ] support opacity slider https://github.com/terriajs/terriajs/issues/5044

**Comment by AnaBelgun** [comment]
superseded  by June release
