### ISSUE TITLE
NEII - Jun 2021 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#184]
- [ ] fail to load in EI (?)
- [ ] text breaking for NEMSR descriptions https://github.com/TerriaJS/neii-viewer/issues/163
- [ ] unknown tile error when accessing services under Air and Water data groups: https://github.com/TerriaJS/neii-viewer/issues/162 
- [ ] error retrieving multiple layers / might be error handling issue: https://github.com/TerriaJS/neii-viewer/issues/161
